version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    ports:
      - 8000:8000
    volumes:
      - .:/sns
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: database
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    
volumes:
  postgres_data:
